/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Book { 
    description?: string;
    id?: number;
    imageUrl?: string;
    isbn?: string;
    language?: Book.LanguageEnum;
    nbOfPages?: number;
    publicationDate?: Date;
    title?: string;
    unitCost?: number;
}
export namespace Book {
    export type LanguageEnum = 'ENGLISH' | 'FRENCH' | 'SPANISH' | 'ITALIAN' | 'HINDI' | 'MARATHI';
    export const LanguageEnum = {
        ENGLISH: 'ENGLISH' as LanguageEnum,
        FRENCH: 'FRENCH' as LanguageEnum,
        SPANISH: 'SPANISH' as LanguageEnum,
        ITALIAN: 'ITALIAN' as LanguageEnum,
        HINDI: 'HINDI' as LanguageEnum,
        MARATHI: 'MARATHI' as LanguageEnum
    };
}
